// Deterministic tag chip coloring. Hash on tag.id (rename-safe, spatial-memory
// preserved) with FNV-1a 32-bit -> curated 16-pair tinted-neutral palette.
// Every pair clears WCAG AA 4.5:1 contrast (see tagChipStyle.test.ts).

export interface TagChipStyle {
  background: string;
  color: string;
}

// Curated palette: 16 pairs generated by walking the OKLCH hue wheel in
// ~22.5° steps starting at h=20°, so consecutive hash buckets land on
// visibly distinct colors instead of clustering in a narrow band. Each
// entry pairs a soft tinted background (L≈0.945, C≈0.028) with a deep
// desaturated foreground (L≈0.32, C≈0.07) at the same hue. Chroma stays
// ≤0.08 so chips remain in the tinted-neutral register and never compete
// with `--kanso-accent` for attention (DESIGN.md hard constraint). Hex
// baked here — WebKit's OKLCH implementation has quirks in the Tauri
// WebView. All pairs verified against WCAG AA (contrast ≥ 4.5:1) in the
// companion test; the palette actually sits well above 10:1.
const PALETTE: readonly TagChipStyle[] = [
  { background: '#ffe6e5', color: '#512224' }, // rose
  { background: '#fee7de', color: '#502513' }, // salmon
  { background: '#fbeada', color: '#4b2a02' }, // amber
  { background: '#f5ecd8', color: '#423000' }, // sand
  { background: '#edefda', color: '#353500' }, // olive
  { background: '#e6f1de', color: '#253a11' }, // lime
  { background: '#dff3e5', color: '#0c3d22' }, // sage
  { background: '#daf3ed', color: '#003e32' }, // mint
  { background: '#d8f3f4', color: '#003d41' }, // teal
  { background: '#daf2fb', color: '#003a4c' }, // cyan
  { background: '#deefff', color: '#0c3654' }, // sky
  { background: '#e4edff', color: '#233156' }, // steel
  { background: '#eceaff', color: '#332c54' }, // periwinkle
  { background: '#f3e8fb', color: '#3f274c' }, // lavender
  { background: '#fae6f4', color: '#482441' }, // mauve
  { background: '#fee6ed', color: '#4e2233' }, // blush
] as const;

// FNV-1a 32-bit over UTF-8 bytes of `tagId`. Zero-dep, deterministic, and
// distributes short ASCII (UUIDs, ULIDs) evenly across the palette.
function fnv1a(str: string): number {
  let hash = 0x811c9dc5;
  const bytes = new TextEncoder().encode(str);
  for (let i = 0; i < bytes.length; i++) {
    hash ^= bytes[i]!;
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash >>> 0;
}

export function tagChipStyle(tagId: string): TagChipStyle {
  const idx = fnv1a(tagId) % PALETTE.length;
  return PALETTE[idx]!;
}

// Exported for tests only.
export const __palette = PALETTE;
