// Deterministic tag chip coloring. Hash on tag.id (rename-safe, spatial-memory
// preserved) with FNV-1a 32-bit -> curated 24-pair tinted-neutral palette.
// Every pair clears WCAG AA 4.5:1 contrast (see tagChipStyle.test.ts).

export interface TagChipStyle {
  background: string;
  color: string;
}

// Curated palette: 24 pairs generated by walking the OKLCH hue wheel in
// 15° steps starting at h=15°, then permuted with a coprime stride of 7
// so adjacent bucket indices land on hues ~105° apart. That protects the
// spatial-memory promise when consecutively-created tags happen to hash
// into neighbouring buckets (ULID prefixes cluster in time). Each pair
// pins a soft tinted background (L≈0.945, C≈0.028) to a deep desaturated
// foreground (L≈0.32, C≈0.07) at the same hue. Chroma stays ≤0.08 so
// chips remain in the tinted-neutral register and never compete with
// `--kanso-accent` for attention (DESIGN.md hard constraint). Hex baked
// here — WebKit's OKLCH implementation has quirks in the Tauri WebView.
// Verified against WCAG AA (contrast ≥ 4.5:1) in the companion test; the
// palette actually sits well above 10:1.
const PALETTE: readonly TagChipStyle[] = [
  { background: '#ffe6e7', color: '#512227' }, // rose
  { background: '#eaf0db', color: '#2e3806' }, // moss
  { background: '#daf1fb', color: '#00394d' }, // cyan
  { background: '#f8e6f6', color: '#462444' }, // lilac
  { background: '#f8ebd9', color: '#472d00' }, // amber
  { background: '#daf3ed', color: '#003e34' }, // mint
  { background: '#eaebff', color: '#302d55' }, // iris
  { background: '#ffe6e2', color: '#51231d' }, // coral
  { background: '#e5f1df', color: '#223a13' }, // lime
  { background: '#ddf0fe', color: '#043753' }, // sky
  { background: '#fce6f1', color: '#4b233b' }, // mauve
  { background: '#f4ecd8', color: '#413000' }, // wheat
  { background: '#d8f3f3', color: '#003d3e' }, // teal
  { background: '#efe9fd', color: '#392a51' }, // periwinkle
  { background: '#fee8de', color: '#4f2611' }, // apricot
  { background: '#e0f3e3', color: '#133c1f' }, // fern
  { background: '#e1eeff', color: '#183356' }, // azure
  { background: '#fee6ec', color: '#4f2231' }, // blush
  { background: '#efeed9', color: '#383400' }, // olive
  { background: '#d8f2f7', color: '#003c46' }, // aqua
  { background: '#f4e8fa', color: '#40274b' }, // violet
  { background: '#fce9db', color: '#4c2905' }, // peach
  { background: '#dcf3e8', color: '#003e2a' }, // sage
  { background: '#e5ecff', color: '#253056' }, // steel
] as const;

// FNV-1a 32-bit over UTF-8 bytes of `tagId`. Zero-dep, deterministic, and
// distributes short ASCII (UUIDs, ULIDs) evenly across the palette.
function fnv1a(str: string): number {
  let hash = 0x811c9dc5;
  const bytes = new TextEncoder().encode(str);
  for (let i = 0; i < bytes.length; i++) {
    hash ^= bytes[i]!;
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash >>> 0;
}

export function tagChipStyle(tagId: string): TagChipStyle {
  const idx = fnv1a(tagId) % PALETTE.length;
  return PALETTE[idx]!;
}

// Exported for tests only.
export const __palette = PALETTE;
